services:
  laravel:
    image: fjmoto_admin_laravel-dev
    container_name: client_laravel
    volumes:
      - ./:/var/www/html
    ports:
      - "2304:80"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=fjmoto-admin
      - DB_USERNAME=root
      - DB_PASSWORD=root