services:
  laravel:
    image: fjmoto_admin_laravel-dev
    container_name: client_laravel
    volumes:
      - ./:/var/www/html
    ports:
      - "2304:80"
    networks:
      - connect
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "2609:3306"
    environment:
      MYSQL_DATABASE: fjmoto-admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - connect

volumes:
  mysql-data:


networks:
  connect:
    driver: bridge
