services:
    laravel:
        image: laravel
        container_name: client-site
        volumes:
            - ./:/var/www/html
            - ../storage/hydrogen:/var/www/html/public/hydrogen
        ports:
            - "2304:80"
        networks:
            - cliff-network

networks:
    cliff-network:
        external: true
        name: cliff-network
